server:
  port: 8080

spring:
  application:
    name: back

  profiles:
    include: secret
    active: dev

  output:
    ansi:
      enabled: always

  flyway:
    enabled: true
    baseline-on-migrate: false
    locations: classpath:db/migration

  jpa:
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
        jdbc:
          time_zone: Asia/Seoul
    open-in-view: false

  jackson:
    deserialization:
      fail-on-unknown-properties: false
    time-zone: Asia/Seoul

  threads:
    virtual:
      enabled: true

app:
  front-base-url: ${FRONT_BASE_URL:http://localhost:3000}

  device:
    max-sessions-per-user: 10
    max-trusted-devices: 5

notification:
  dispatcher: async

trace:
  strict-mode: false

logging:
  level:
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.orm.jdbc.extract: TRACE

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs

  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
    display-request-duration: true

  default-produces-media-type: application/json
  default-consumes-media-type: application/json