spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

  flyway:
    locations: classpath:db/migration

trace:
  strict-mode: true

logging:
  level:
    com.han.back: INFO
    org.hibernate.orm.jdbc.bind: OFF
    org.hibernate.orm.jdbc.extract: OFF

  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] [%X{traceId:-UNTRACED}] [%X{loginId:-}] %-5level %logger{36} - %msg%n"

app:
  device:
    max-sessions-per-user: 10
    max-trusted-devices: 5

springdoc:
  api-docs:
    enabled: false

  swagger-ui:
    enabled: false